### ISSUE TITLE
Create two endpoints

### ISSUE THREAD

**Issue by balinskia** [chaindevs/binance-analytics#4]
`GET /getAllTransactions` - should return a list of all transactions
`POST /transaction` - should add a new transaction to the databe

You can test the `GET` by going to the url: `localhost:3000/getAllTransactions` and you should see there all of the transactions that are currently in the db.

You can test the `POST` request by using curl:
```
curl -d '{"date":"11.11.2012", "price":"22"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data
```

**Comment by MastalerzKamil** [comment]
https://github.com/xavism/nestjs-crud
This example working well on my PC.

**Comment by MastalerzKamil** [comment]
To do: use example from link above
